### ISSUE TITLE
TraceInput class implementation

### ISSUE THREAD

**Issue by lachlangrose** [QGeoTrace/GeoTrace2#2]
I'm a bit confused by 

```Python
class TraceInput( QgsMapToolEmitPoint ):

    # state variables for trace tool
    cost = None # input cost layer (raster)
    output = None # output layer (polyline)
    rubberBand = None # control points
    rubberBandLine = None # line visualisation of least-cost path
    history = None # growing list of points added to path
    segments = {} # dictionary to store segment routes in
```
Are you trying to make the traceinput a singleton? Would it better to use a TraceInput builder or factory that will return a new instance of the class or return the current instance if one is available? This way the variables can belong to the instance of the class but only one instance is possible

**Comment by samthiele** [comment]
Is messy coding I guess, but I just want to make sure all those variables are initialised (as none). I see no reason that TraceInput has to be a singleton.

**Comment by samthiele** [comment]
Really? I thought initialising variables within the class definition was the same as in the `constructor?` 

E.g., see the following:

```
class foo:
    x = 10
    def __init__(self):
        z = 30
        
# instance A
A = foo()
print("A.x is initialised to ", A.x)
A.x = 15 
print("A.x is changed to ", A.x)

print("---")
# instance B
B = foo()
print("B.x is initialised to ", B.x)
B.x = 20
print("B.x is chagned to ", B.x)
print("A.x remains unchanged at ", A.x)
```

Clearly A and B are not singletons?

```
A.x is initialised to  10
A.x is changed to  15
---
B.x is initialised to  10
B.x is chagned to  20
A.x remains unchanged at  15
```

**Comment by lachlangrose** [comment]
Well I didn't expect that....

What i think is happening is the class attribute x is not being used when you set it to be a value. So basically you are adding an instance attribute that has the value being printed. This means that when you ask for the attribute value its what you expect.

If you try setting the attribute to a mutable type and do a change to it the changes are propagated through all instances of the class.

```
class A:
  a=None
  b=[]
a = A()
a.a=10
a.b.append(10)
b = A()
b.a
b.b.append(11)
print(b.b)
``` 
Which returns [10,11]


Anyway its not doing exactly what I thought but you can see what I mean.

**Comment by samthiele** [comment]
Hmmmm, very curious indeed! I guess python handles primitives and object references differently somehow. Anyway - will put those initialisations in the constructor, then it's clear what's going on :-)
