### ISSUE TITLE
raster to numpy

### ISSUE THREAD

**Issue by lachlangrose** [QGeoTrace/GeoTrace2#3]
I've made a test to check whether the raster loaded through qgis is the same as if it was loaded using PIL. It's failing and I'm not sure why, I remember there being issues with the rotation of the arrays. @samthiele do you have any ideas?

**Comment by samthiele** [comment]
Resolved; problem was due to nan? pixels at the edge of the array that were being loaded differently. Now test only looks at a section of the interior of the test image.
